// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwiTvApS7gsD_PvwrNg51cWMe5l9OQyoI',
    appId: '1:733101653489:web:77fd4bb0ad88d49985d850',
    messagingSenderId: '733101653489',
    projectId: 'guru-e-jurnal',
    authDomain: 'guru-e-jurnal.firebaseapp.com',
    storageBucket: 'guru-e-jurnal.appspot.com',
    measurementId: 'G-FC2V4L7YFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycVEtRejwS_1bhxk8vUG52JwJmi2uZ_8',
    appId: '1:733101653489:android:c6f2344e27bcc08385d850',
    messagingSenderId: '733101653489',
    projectId: 'guru-e-jurnal',
    storageBucket: 'guru-e-jurnal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWpAHezf6HZ6QCWIiEu5QsYkbxKORbOsw',
    appId: '1:733101653489:ios:3142d22fbcc1744d85d850',
    messagingSenderId: '733101653489',
    projectId: 'guru-e-jurnal',
    storageBucket: 'guru-e-jurnal.appspot.com',
    iosClientId: '733101653489-p1pog6jp0c89vvdkn7ebnfg1ega0cj38.apps.googleusercontent.com',
    iosBundleId: 'com.example.guruEjurnal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWpAHezf6HZ6QCWIiEu5QsYkbxKORbOsw',
    appId: '1:733101653489:ios:38b1c7baa9b2c22f85d850',
    messagingSenderId: '733101653489',
    projectId: 'guru-e-jurnal',
    storageBucket: 'guru-e-jurnal.appspot.com',
    iosClientId: '733101653489-d918733r31o8i3mj91n5d21u6gk9uvjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.guruEjurnal.RunnerTests',
  );
}
